title: Castlerock Lavender
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://castlerocklavender.com/" # the base hostname & protocol for your site, e.g. http://example.com

uploads_dir: "uploads"


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: page
      permalink: /:basename:output_ext

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - src
  - node_modules
  - gulpfile.js
  - package.json
  - uploads

gems:
  - jekyll-assets

assets:
  compress:
    css: default
    js: default

  prefix: "/assets"

  sources:
    - _assets/css
    - _assets/js
    - _assets/fonts
    - _assets/img
    - uploads

  features:
    automatic_img_size: true
    automatic_img_alt : true
