defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: page
      permalink: /:basename:output_ext

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - src
  - node_modules
  - gulpfile.js
  - package.json

gems:
  - jekyll-assets

assets:
  compress:
    css: default
    js: default

  prefix: "/assets"

  sources:
    - _css
    - img
    - _js
    - _fonts

  features:
    automatic_img_size: true
    automatic_img_alt : true
